question_data = [
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The Great Wall of China is visible from the moon.",
        "correct_answer": "False",
        "incorrect_answers": ["True"]
    },
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Nutella is produced by the German company Ferrero.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "You can legally drink alcohol while driving in Mississippi.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "General Knowledge",
     "type": "boolean",
     "difficulty": "easy",
     "question": "On average, at least 1 person is killed by a drunk driver in the United States every hour.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Pluto is a planet.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Adolf Hitler was born in Australia. ", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "When you cry in space, your tears stick to your face.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "Romanian belongs to the Romance language family, shared with French, Spanish, Portuguese and Italian. ",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "The National Animal of Scotland is the Unicorn.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "A pasodoble is a type of Italian pasta sauce.",
        "correct_answer": "False", "incorrect_answers": ["True"]}]
